CREATE TABLE [dbo].[Property]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [PropertyName] NVARCHAR(MAX) NOT NULL, 
    [Description] NVARCHAR(MAX) NULL,
    [AgentDetails] NVARCHAR(MAX) NULL, 
    [Longitude] NVARCHAR(MAX) NULL, 
    [Latitude] NVARCHAR(MAX) NULL, 
    [Amount] DECIMAL(18, 2) NOT NULL, 
    [PropertyProfile] NVARCHAR(MAX) NULL, 
    [PropertyType] NVARCHAR(MAX) NULL, 
    [PropertyStatus] INT NULL,
    [VerificationStatus] INT NULL,
	[DescriptiveStatus] INT NULL,
	[PropertyAddress] NVARCHAR(MAX) NULL,
	[DateCreated] datetime not null, 
    [IdentificationNumber] NVARCHAR(MAX) NOT NULL,
	 [State] NVARCHAR (450) NULL, 
	 [LGA] NVARCHAR (450) NULL,
	   [Community] NVARCHAR (450) NULL,	
	   [Kindred] NVARCHAR (450) NULL, 
    [SortOrder] INT NULL,
	 [HomeLocation] INT NULL, 
    [Username] NVARCHAR(50) NULL, 
    [Video] NVARCHAR(MAX) NULL, 
    [PropertyLevel] NVARCHAR(MAX) NULL, 
    [MapLink] NVARCHAR(MAX) NULL,

)
